import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function exportInvoicePDF(inv) {
  const doc = new jsPDF();
  const ink = [76, 29, 149];
  const violet = [139, 92, 246];

  doc.setFillColor(...ink);
  doc.rect(0, 0, 210, 18, 'F');
  doc.setFillColor(...violet);
  doc.rect(0, 18, 210, 1.5, 'F');
  doc.setTextColor(139, 92, 246);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Lexa', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(196, 181, 253);
  doc.text('Practice Intelligence', 14, 16.5);

  doc.setTextColor(...ink);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 140, 32);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text(inv.invoiceNumber, 140, 40);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Billed To', 14, 32);
  doc.setFont('helvetica', 'normal');
  const clientName = `${inv.client?.firstName || ''} ${inv.client?.lastName || ''}`.trim();
  doc.text(clientName + (inv.client?.company ? ` (${inv.client.company})` : ''), 14, 39);
  if (inv.case?.title) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Matter: ${inv.case.title}`, 14, 46);
  }

  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  const issued = inv.createdAt ? new Date(inv.createdAt).toLocaleDateString() : '—';
  const due = inv.dueDate ? new Date(inv.dueDate).toLocaleDateString() : '—';
  doc.text(`Issued: ${issued}`, 140, 48);
  doc.text(`Due: ${due}`, 140, 54);
  doc.text(`Billing: ${(inv.billingType || 'hourly').replace('-', ' ')}`, 140, 60);

  const rows = (Array.isArray(inv.lineItems) ? inv.lineItems : []).map(li => {
    if (inv.billingType === 'hourly') {
      return [li.description || '—', `${li.hours || 0}h`, `$${Number(li.rate || 0).toFixed(2)}/hr`, `$${Number(li.amount || 0).toFixed(2)}`];
    }
    return [li.description || '—', '—', '—', `$${Number(li.amount || 0).toFixed(2)}`];
  });

  autoTable(doc, {
    startY: 70,
    head: [inv.billingType === 'hourly' ? ['Description', 'Hours', 'Rate', 'Amount'] : ['Description', '', '', 'Amount']],
    body: rows.length ? rows : [['—', '—', '—', '—']],
    headStyles: { fillColor: ink, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [250, 248, 244] },
    columnStyles: { 0: { cellWidth: 90 }, 1: { halign: 'center', cellWidth: 20 }, 2: { halign: 'right', cellWidth: 35 }, 3: { halign: 'right', cellWidth: 35 } },
    margin: { left: 14, right: 14 },
  });

  const finalY = doc.lastAutoTable.finalY + 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text('Subtotal:', 140, finalY);
  doc.text(`$${Number(inv.subtotal || 0).toFixed(2)}`, 196, finalY, { align: 'right' });
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ink);
  doc.text('Total:', 140, finalY + 12);
  doc.text(`$${Number(inv.total || 0).toFixed(2)}`, 196, finalY + 12, { align: 'right' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Lexa — lexa-suite.vercel.app', 105, 285, { align: 'center' });

  doc.save(`${inv.invoiceNumber}.pdf`);
}
